### ISSUE TITLE
Add icon.png for package listing

### ISSUE THREAD

**Issue by pelikhan** [minodekit/pxt-minode#3]
The icon should be sized with a 16:9 ratio and of at least 184 pixel wide. It is used in the package list in the editor,

![image](https://user-images.githubusercontent.com/4175913/28526763-5a0859da-703d-11e7-88f5-5e712af6fb0e.png)

**Comment by ahnniu** [comment]
Thanks @pelikhan. 

Fixed that and created a tag 'v1.0.2'

**Comment by ahnniu** [comment]
Closed.
